name: 'get-next-version'
description: >
  Gets the next version for your repository according to SemVer
  (semantic versioning) based on conventional commits.
outputs:
  version:
    description: 'Next version'
runs:
  using: 'docker'
  image: 'Dockerfile'
