name: 'get-next-version'
description: >
  Calculates the next version of your project based on conventional
  commits and tags the repository with the new version.
outputs:
  version:
    description: 'New semantic version for the repository'
runs:
  using: 'docker'
  image: 'Dockerfile'
