name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  qa:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Calculate next version
      uses: ./
