name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  qa:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get next version
      id: get_next_version
      uses: ./
    - name: Release a new version
      if: ${{ steps.get_next_version.outputs.hasNextVersion }} == 'true'
      run: |
        NEXT_VERSION=${{ steps.get_next_version.outputs.version }}

        git tag $NEXT_VERSION
        git push origin $NEXT_VERSION
