name: Release

on:
  push:
    branches:
      - 'main'
  pull_request: {}

jobs:
  qa:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.base_ref }}
    - name: Calculate next version
      uses: ./
