name: Release

on:
  push:
    branches:
      - 'main'
  pull_requst: {}

jobs:
  qa:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Calculate next version
      uses: ./
