name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  qa:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    - name: Get next version
      id: get_next_version
      uses: ./
    - name: Create new version
      if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
      run: |
        NEXT_VERSION=${{ steps.get_next_version.outputs.version }}

        git tag $NEXT_VERSION
        git push origin $NEXT_VERSION
    - name: Build artifacts
      if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
      run: |
        make build-all
    - name: Release new version
      if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/*"
        tag: ${{ steps.get_next_version.outputs.version }}
