name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  qa:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Use Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    - name: Run QA
      run: make
